name: $mname
services:
   mariadb:
      image: $MARIADB_IMAGE
      privileged: true
      restart: unless-stopped
      networks:
         - backend
      environment:
         - MARIADB_ROOT_PASSWORD=${ROOT_PASSWORD:-password}
         - MARIADB_USER=${DB_USERNAME:-moodleuser}
         - MARIADB_PASSWORD=${DB_PASSWORD:-password}
         - MARIADB_DATABASE=${DB_NAME:-moodle}
         - MARIADB_CHARACTER_SET=utf8mb4
         - MARIADB_COLLATE=utf8mb4_unicode_ci
         - MARIADB_SKIP_TEST_DB=yes
      volumes:
         - /etc/localtime:/etc/localtime:ro
         - $MDL_ENVS_DIR/$mname/backup.sql:/docker-entrypoint-initdb.d/restore-the-backup.sql:ro
         - db:/bitnami/mariadb
   moodle:
      image: $MOODLE_IMAGE
      privileged: true
      restart: unless-stopped
      ports:
        - $MOODLE_PORT:8080
      depends_on:
         - mariadb
      networks:
         - backend
      environment:
         - MOODLE_DATABASE_HOST=mariadb
         - MOODLE_DATABASE_PORT_NUMBER=3306
         - MOODLE_DATABASE_USER=${DB_USERNAME:-moodleuser}
         - MOODLE_DATABASE_PASSWORD=${DB_PASSWORD:-password}
         - MOODLE_DATABASE_NAME=${DB_NAME:-moodle}
         - MOODLE_SKIP_BOOTSTRAP=yes
         - MOODLE_HOST=${MOODLE_HOST:-localhost}
      volumes:
         - /etc/localtime:/etc/localtime:ro
         - $MDL_ENVS_DIR/$mname/src:/bitnami/moodle
         - $MDL_ENVS_DIR/$mname/data:/bitnami/moodledata
networks:
   backend:
volumes:
   db:
