name: $mname
services:
   mariadb:
      image: $MARIADB_IMAGE
      privileged: true
      restart: unless-stopped
      networks:
         - backend
      environment:
         - MARIADB_ROOT_PASSWORD=${ROOT_PASSWORD:-password}
      volumes:
         - /etc/localtime:/etc/localtime:ro
         - db:/bitnami/mariadb
   moodle:
      image: $MOODLE_IMAGE
      privileged: true
      restart: unless-stopped
      ports:
        - $MOODLE_PORT:8080
      depends_on:
         - mariadb
      networks:
         - backend
      environment:
         - MOODLE_DATABASE_HOST=mariadb
         - MOODLE_DATABASE_PORT_NUMBER=3306
         - MOODLE_DATABASE_USER=${DB_USERNAME:-moodleuser}
         - MOODLE_DATABASE_PASSWORD=${DB_PASSWORD:-password}
         - MOODLE_DATABASE_NAME=${DB_NAME:-moodle}
         - MOODLE_SKIP_BOOTSTRAP=yes
         - MOODLE_HOST=${MOODLE_HOST:-localhost}
      volumes:
         - /etc/localtime:/etc/localtime:ro
         - src:/bitnami/moodle
         - data:/bitnami/moodledata
networks:
   backend:
volumes:
   db:
   src:
   data:
